name: gitactiondemo 
on:
  push:
    branches:
      - main
  jobs:
      job-demo:
          runs-on: ubuntu latest
          
          steps:
              - name: checkout code
                uses: actions/checkout@v2

              - name: print massage 
                run: echo "welcome to gitaction"
